### PR TITLE
Modern build system and new XmlRpcType instance

### PR DESCRIPTION
**Pull request by akru**
Changes:

* Stack (http://haskellstack.org) build system support
* Added `Text` instance for `XmlRpcType` typeclass

### CODE REVIEW

**Comment by byorgey** [comment]
Thanks!

**Comment by akru** [comment]
I see this has build troubles with GHC before `7.10.3` because `Applicative` isn't base of `Monad` in older versions, do is critical?

**Comment by akru** [comment]
Oh yea, I see https://github.com/byorgey/haxr/commit/3add7fdbffc18a72c0f7d9b2a122e86e5495a784, thank you!

**Comment by byorgey** [comment]
Released as `3000.11.2`.

**Pull request merged**
