### PR TITLE
allow base-4.16 for ghc-9.2

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Comment by juhp** [comment]
Not sure why the 9.2 build failed mysteriously in CI here.
It builds for me in latest Stackage Nightly anyway.

It would be nice to have a Hackage revision done too.

**Comment by juhp** [comment]
Yay CI seems all good now

**Comment by byorgey** [comment]
Thanks!  Published a new Hackage revision.

**Comment by juhp** [comment]
I re-enabled it in Stackage Nightly :+1:

**Pull request merged**
