### PR TITLE
Release 4000

### PR DESCRIPTION
**Pull request by akru**
I start with https://github.com/byorgey/haxr/issues/18 for migrate to `Text` driven XML parser, use `TagSoup`. But a lot of places is changed.

Full list of changes is:
- Use Text everywhere
- TagSoup XML parser / render
- Simple and clean HTTP client with HTTPS and Basic Auth support
- Stand-alone Snap driven web-server

### CODE REVIEW

**Comment by byorgey** [comment]
Wow, thank you for this hard work!  Unfortunately I am currently in Japan attending ICFP so I will probably not have time to look at this carefully for a couple weeks.

**Comment by byorgey** [comment]
Hi, sorry it has taken me so long to get around to looking at this.  However, now that I start looking at it, although I can tell there is some great stuff there, your changes are hard to review, specifically because commit @8bcf648a both moved a bunch of files *and* edited them, so diff just shows some files entirely deleted and others entirely added, making it very difficult to see what has changed.  It will probably take me a while to look through everything.

**Comment by byorgey** [comment]
Also, so many things are changed that it is hard to keep everything straight.  It would really help if you could provide a more detailed explanation of what has changed, along with a justification for each change.  I know `haxr` was really in need of updating, but I don't just want to change everything just for the sake of changing.  We also need to worry about providing a sensible upgrade path for users.

**Comment by akru** [comment]
You are absolutely right, 
the history of changes is really difficult to review because I take a long time between commits, it's my mistake. The changes as great as maybe right to see it like a new project with `haxr 3000.*` compatible interface.

I really rewrite `Client.hs`, `Server.hs` and `Internals.hs` at all, but I care about compatibility as possible.

Why so many changes is needed?

 * Migration to `tagsoup` Text XML parser/builder in `Internals.hs` takes a lot of changes;
 * Migration to `http-client` as HTTP/s client in `Client.hs` - is really minimize the client code;
 * Migration to `snap` as HTTP server in `Server.hs` - HTTP server out of the box.

Maybe for backward compatibility CGI server is required to implement also.

**Comment by byorgey** [comment]
Hi there, sorry for taking so long to respond again.  In the end the fact is that I just don't have the bandwidth to really work on this or evaluate the changes.  I took over maintaining `haxr` just because I need it for another package of mine (`BlogLiterately`).

Here's my suggestion for moving forward: why don't you take your updated version and just release it as a new package.  For example you might call it `haxr-ng` or something like that---a name which somehow makes it clear it is a new version of `haxr`.  But then you could worry about maintaining that version, and users could migrate if and when they are ready.  Do you think that makes sense?

**Comment by akru** [comment]
Hi! Thank you for response!

Yep, may be make another project will be better, currently I have a fork at [RoboticsHS](https://github.com/RoboticsHS/haxr). 
May be I change name and push release to the hackage in the future.

Thank you @byorgey!

**Pull request closed without merging**
